---
name: test-with
on:
  pull_request:

jobs:
  get-matrix:
    runs-on: ubuntu-latest
    name: get-matrix
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      has_refs: ${{ steps.set-matrix.outputs.has_refs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch matrix
        id: set-matrix
        uses: ./
        with:
          repository_default_branch: master
          branches: master
          tags: v0.1.0
          num_latest_tags: 1

  info:
    needs: [get-matrix]
    runs-on: ubuntu-latest
    name: info
    steps:
      - name: Show outputs
        run: |
          echo 'matrix=${{ needs.get-matrix.outputs.matrix }}'
          echo 'has_refs=${{ needs.get-matrix.outputs.has_refs }}'

  build:
    needs: [get-matrix]
    runs-on: ubuntu-latest
    name: build
    strategy:
      fail-fast: false
      matrix:
        refs:
          - ${{ fromJson(needs.get-matrix.outputs.matrix) }}
    steps:
      - name: "[SETUP] Checkout repository (ref: ${{ matrix.refs }})"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ matrix.refs }}
      - name: Show git
        run: |
          git log | head -20
